language: node_js
node_js:
  - "10"
dist: trusty
sudo: required
branches:
  only:
    - master
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.4
  - export PATH="$HOME/.yarn/bin:$PATH"
before_script:
  - yarn add global --silent @angular/cli@9.1.1
script:
  - ng lint
  - ng build

